---
ffg:
    archetypes:
        -
            name: Human
            characteristics:
                Brawn: 2
                Agility: 2
                Intellect: 2
                Cunning: 2
                Willpower: 2
                Presence: 2
            wound: 10
            strain: 10
            xp: 100
            skills: []
            talents: []
        -
            name: Laborer
            characteristics:
                Brawn: 3
                Agility: 2
                Intellect: 2
                Cunning: 2
                Willpower: 1
                Presence: 2
            wound: 12
            strain: 8
            xp: 100
            skills:
                - Athletics
            talents: []
        -
            name: Intellectual
            characteristics:
                Brawn: 2
                Agility: 1
                Intellect: 3
                Cunning: 2
                Willpower: 2
                Presence: 2
            wound: 8
            strain: 12
            xp: 100
            skills:
                - Knowledge
            talents: []
        -
            name: Aristocrat
            characteristics:
                Brawn: 1
                Agility: 2
                Intellect: 2
                Cunning: 2
                Willpower: 2
                Presence: 3
            wound: 10
            strain: 10
            xp: 100
            skills:
                - Cool
            talents: []
        

            
