ffg:
    skills: 
        - 
            name: Athletics
            description: "General fitness and tasks like running, climbing, etc."
            characteristic: Brawn
        -
            name: Brawl
            description: Fighting without weapons.
            characteristic: Brawn
        -
            name: Charm
            description: "Compliment, flatter, woo, and make people like you."
            characteristic: Presence
        -
            name: Coercion
            description: "Instill obedience through threats or violence."
            characteristic: Willpower
        -
            name: Cool
            description: Maintaining composure in tough situations.
            characteristic: Presence
        -
            name: Coordination
            description: Steadiness, balance and flexibility.
            characteristic: Agility
        -
            name: Deception
            description: Lying to or tricking someone.
            characteristic: Cunning
        -
            name: Discipline
            description: "Focus, fortitude, and mental resistance."
            characteristic: Willpower
        -
            name: Knowledge
            description: General knowledge and education.
            characteristic: Intellect
        -
            name: Leadership
            description: Instilling authority in others.
            characteristic: Presence
        -
            name: Mechanics
            description: "Build, disassemble or repair mechanical objects."
            characteristic: Intellect
        -
            name: Medicine
            description: Healing other characters.
            characteristic: Intellect
        -
            name: Melee
            description: Fighting with melee weapons.
            characteristic: Brawn
        -
            name: Negotiation
            description: Making deals.
            characteristic: Presence
        -
            name: Perception
            description: Using senses to observe surroundings.
            characteristic: Cunning
        -
            name: Ranged Light
            description: Fighting with ranged weapons.
            characteristic: Agility
        -
            name: Resilience
            description: Overcome pain and fight through fatigue.
            characteristic: Brawn
        -
            name: Skulduggery
            description: "Engaging in covert or criminal activity, such as picking locks."
            characteristic: Cunning
        -
            name: Stealth
            description: Going unnoticed.
            characteristic: Agility
        -
            name: Streetwise
            description: Thrive in rough or dangerous urban areas.
            characteristic: Cunning
        -
            name: Survival
            description: Survive in rough or dangerous outdoor areas.
            characteristic: Cunning
        -
            name: Vigilance
            description: Being aware of surroundings.
            characteristic: Willpower
