---
ffg:
    careers:
        - 
            name: Entertainer
            career_skills:
                - Charm
                - Coordination
                - Deception
                - Discipline
                - Leadership
                - Melee
                - Skulduggery
                - Stealth
        -
            name: Explorer
            career_skills:
                - Athletics
                - Brawl
                - Coordination
                - Deception
                - Perception
                - Ranged Light
                - Stealth
                - Survival
        -
            name: Healer
            career_skills:
                - Cool
                - Discipline
                - Knowledge
                - Medicine
                - Melee
                - Resilience
                - Survival
                - Vigilance
        - 
            name: Leader
            career_skills:
                - Charm
                - Coercion
                - Cool
                - Discipline
                - Leadership
                - Melee
                - Negotiation
                - Perception
        -
            name: Scoundrel
            career_skills:
                - Charm
                - Cool
                - Coordination
                - Deception
                - Ranged Light
                - Skulduggery
                - Stealth
                - Streetwise
        -
            name: Socialite
            career_skills:
                - Charm
                - Cool
                - Deception
                - Knowledge
                - Negotiation
                - Perception
                - Streetwise
                - Vigilance
        -
            name: Soldier
            career_skills:
                - Athletics
                - Brawl
                - Coercion
                - Melee
                - Perception
                - Ranged Light
                - Survival
                - Vigilance
        -
            name: Tradesperson
            career_skills:
                - Athletics
                - Brawl
                - Discipline
                - Mechanics
                - Negotiation
                - Perception
                - Resilience
                - Streetwise
            
