ffg:
    talents: 
        - 
            name: Bought Info
            tier: 1
            ranked: false
        - 
            name: Clever Retort
            tier: 1
            ranked: false
        -
            name: Defensive Sysops
            tier: 1
            ranked: false
        -
            name: Desperate Recovery
            tier: 1
            ranked: false
        -
            name: Duelist
            tier: 1
            ranked: false
        -
            name: Durable
            tier: 1
            ranked: true
        -
            name: Forager
            tier: 1
            ranked: false
        -
            name: Grit
            tier: 1
            ranked: true
        -
            name: Hamstring Shot
            tier: 1
            ranked: false
        -
            name: Jump Up
            tier: 1
            ranked: false
        -
            name: Knack For It
            tier: 1
            ranked: true
        -
            name: Know Somebody
            tier: 1
            ranked: true
        -
            name: Let's Ride
            tier: 1
            ranked: false
        -
            name: One With Nature
            tier: 1
            ranked: false
        -
            name: Parry
            tier: 1
            ranked: true
        -
            name: Proper Upbringing
            tier: 1
            ranked: true
        -
            name: Quick Draw
            tier: 1
            ranked: false
        -
            name: Quick Strike
            tier: 1
            ranked: true
        -
            name: Rapid Reaction
            tier: 1
            ranked: true
        -
            name: Second Wind
            tier: 1
            ranked: true
        -
            name: Surgeon
            tier: 1
            ranked: true
        -
            name: Swift
            tier: 1
            ranked: false
        -
            name: Toughened
            tier: 1
            ranked: true
        -
            name: Unremarkable
            tier: 1
            ranked: false
        -
            name: Basic Military Training
            tier: 2
            ranked: false
        -
            name: Berserk
            tier: 2
            ranked: false
        -
            name: Coordinated Assault
            tier: 2
            ranked: true
        -
            name: Counteroffer
            tier: 2
            ranked: false
        -
            name: Daring Aviator
            tier: 2
            ranked: true
        -
            name: Defensive Stance
            tier: 2
            ranked: true
        -
            name: Dual Wielder
            tier: 2
            ranked: false
        -
            name: Fan The Hammer
            tier: 2
            ranked: false
        -
            name: Heightened Awareness
            tier: 2
            ranked: false
        -
            name: Defensive Sysops Improved
            tier: 2
            ranked: false
            prereq: Defensive Sysops
        -
            name: Inspiring Rhetoric
            tier: 2
            ranked: false
        -
            name: Inventor
            tier: 2
            ranked: true
        -
            name: Lucky Strike
            tier: 2
            ranked: false
        -
            name: Scathing Tirade
            tier: 2
            ranked: false
        -
            name: Side Step
            tier: 2
            ranked: true
        -
            name: Animal Companion
            tier: 3
            ranked: true
        -
            name: Barrel Roll
            tier: 3
            ranked: false
        -
            name: Distincitive Style
            tier: 3
            ranked: false
        -
            name: Dodge
            tier: 3
            ranked: true
        -
            name: Eagle Eyes
            tier: 3
            ranked: false
        -
            name: Field Commander
            tier: 3
            ranked: false
        -
            name: Forgot To Count
            tier: 3
            ranked: false
        -
            name: Full Throttle
            tier: 3
            ranked: false
        -
            name: Grenadier
            tier: 3
            ranked: true
        -
            name: Inspiring Rhetoric Improved
            tier: 3
            ranked: false
            prereq: Inspiring Rhetoric
        -
            name: Painkiller Specialization
            tier: 3
            ranked: true
        -
            name: Scathing Tirade Improved
            tier: 3
            ranked: false
            prereq: Scathing Tirade
        -
            name: Heroic Will
            tier: 3
            ranked: false
        -
            name: Natural
            tier: 3
            ranked: false
        -
            name: Parry Improved
            tier: 3
            ranked: false
            prereq: Parry
        -
            name: Can't We Talk About This
            tier: 4
            ranked: false
        -
            name: Deadeye
            tier: 4
            ranked: false
        -
            name: Defensive
            tier: 4
            ranked: true
        -
            name: Defensive Driving
            tier: 4
            ranked: true
        -
            name: Enduring
            tier: 4
            ranked: true
        -
            name: Field Commander Improved
            tier: 4
            ranked: false
            prereq: Field Commander
        -
            name: How Convenient
            tier: 4
            ranked: false
        -
            name: Inspiring Rhetoric Supreme
            tier: 4
            ranked: false
            prereq: Inspiring Rhetoric Improved
        -
            name: Mad Inventor
            tier: 4
            ranked: false
        -
            name: Overcharge
            tier: 4
            ranked: false
        -
            name: Scathing Tirade Supreme
            prereq: Scathing Tirade Improved
            tier: 4
            ranked: false
        -
            name: Dedication
            tier: 5
            ranked: true
        -
            name: Indomitable
            tier: 5
            ranked: false
        -
            name: Master
            tier: 5
            ranked: false
        -
            name: Overcharge Improved
            tier: 5
            ranked: false
            prereq: Overcharge
        -
            name: Ruinous Repartee
            tier: 5
            ranked: false